name: foxdevtactics/mb65
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
    - '8000:80'
    volumes:
      - ./backend/static:/app/static
    environment:
      - API_ENV=development
    restart: unless-stopped
    networks:
      - app-network
  frontend:
    build: 
      context: ./frontend
    container_name: nextjs-frontend
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
networks:
 app-network:
   driver: bridge